id: P64DDF66D
initial_creation_type: input
source_metadata:
  title: 'MSV 6,05: Ṣoḍaśaka'
  language: bo
  volumes:
    dde27d4a22334317a18b94e8808c5918:
      title: Ṣoḍaśaka
      base_file: Ṣoḍaśaka.txt
      work_id: W61146B4F
  chapter_to_tile: {}
created_at: '2022-03-01T22:55:28.760414'
last_modified_at: '2022-03-01T22:55:28.760421'
